"""Migração Inicial

Revision ID: bc18bfc763a2
Revises: 
Create Date: 2024-11-22 09:23:46.692095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc18bfc763a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editora',
    sa.Column('id_editora', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_editora')
    )
    op.create_table('revistas',
    sa.Column('id_revista', sa.Integer(), nullable=False),
    sa.Column('id_editora', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('edicao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_editora'], ['editora.id_editora'], ),
    sa.PrimaryKeyConstraint('id_revista')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revistas')
    op.drop_table('editora')
    # ### end Alembic commands ###
